name: libphonenumber
description: A Flutter implementation of libphonenumber. Includes core functionality for number parsing, formatting, and validation.
version: 3.0.0
homepage: https://github.com/hnwojtek/flutter-libphonenumber

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.15.0

flutter:
  plugin:
    platforms:
      android:
        package: com.codeheadlabs.libphonenumber
        pluginClass: LibphonenumberPlugin
      ios:
        pluginClass: LibphonenumberPlugin
